"""add_recipe_tables

Revision ID: 2a037d15a76b
Revises: aa09363f0ae9
Create Date: 2025-12-29 18:32:43.564581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a037d15a76b'
down_revision: Union[str, None] = 'aa09363f0ae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meal_type', sa.Enum('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK', name='mealtype'), nullable=False),
    sa.Column('prep_time_minutes', sa.Integer(), nullable=False),
    sa.Column('cook_time_minutes', sa.Integer(), nullable=False),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein_g', sa.Integer(), nullable=False),
    sa.Column('carbs_g', sa.Integer(), nullable=False),
    sa.Column('fat_g', sa.Integer(), nullable=False),
    sa.Column('fiber_g', sa.Integer(), nullable=True),
    sa.Column('sugar_g', sa.Integer(), nullable=True),
    sa.Column('ingredients', sa.JSON(), nullable=True),
    sa.Column('instructions', sa.JSON(), nullable=True),
    sa.Column('diet_tags', sa.JSON(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('times_saved', sa.Integer(), nullable=False),
    sa.Column('total_rating', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recipes_calories', 'recipes', ['calories'], unique=False)
    op.create_index('ix_recipes_featured', 'recipes', ['is_featured'], unique=False)
    op.create_index(op.f('ix_recipes_meal_type'), 'recipes', ['meal_type'], unique=False)
    op.create_index('ix_recipes_protein', 'recipes', ['protein_g'], unique=False)
    op.create_table('user_saved_recipes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('identity_id', sa.String(length=36), nullable=False),
    sa.Column('recipe_id', sa.String(length=36), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_saved_recipes_identity', 'user_saved_recipes', ['identity_id'], unique=False)
    op.create_index(op.f('ix_user_saved_recipes_identity_id'), 'user_saved_recipes', ['identity_id'], unique=False)
    op.create_index('ix_user_saved_recipes_unique', 'user_saved_recipes', ['identity_id', 'recipe_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_saved_recipes_unique', table_name='user_saved_recipes')
    op.drop_index(op.f('ix_user_saved_recipes_identity_id'), table_name='user_saved_recipes')
    op.drop_index('ix_user_saved_recipes_identity', table_name='user_saved_recipes')
    op.drop_table('user_saved_recipes')
    op.drop_index('ix_recipes_protein', table_name='recipes')
    op.drop_index(op.f('ix_recipes_meal_type'), table_name='recipes')
    op.drop_index('ix_recipes_featured', table_name='recipes')
    op.drop_index('ix_recipes_calories', table_name='recipes')
    op.drop_table('recipes')
    # ### end Alembic commands ###
