"""initial schema

Revision ID: 376c6f80292d
Revises: 
Create Date: 2025-12-28 08:45:58.776528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '376c6f80292d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('identity_type', sa.Enum('AUTHENTICATED', 'ANONYMOUS', 'SYSTEM', name='identitytype'), nullable=False),
    sa.Column('provider', sa.Enum('GOOGLE', 'APPLE', 'ANONYMOUS', name='authprovider'), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identities_external_id'), 'identities', ['external_id'], unique=True)
    op.create_table('time_windows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('identity_id', sa.String(length=36), nullable=False),
    sa.Column('window_type', sa.Enum('FAST', 'EATING', 'WORKOUT', 'RECOVERY', name='windowtype'), nullable=False),
    sa.Column('state', sa.Enum('SCHEDULED', 'ACTIVE', 'COMPLETED', 'ABANDONED', name='windowstate'), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_windows_identity_id'), 'time_windows', ['identity_id'], unique=False)
    op.create_index(op.f('ix_time_windows_state'), 'time_windows', ['state'], unique=False)
    op.create_index(op.f('ix_time_windows_window_type'), 'time_windows', ['window_type'], unique=False)
    op.create_table('capabilities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('identity_id', sa.String(length=36), nullable=False),
    sa.Column('capability', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capabilities_identity_id'), 'capabilities', ['identity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_capabilities_identity_id'), table_name='capabilities')
    op.drop_table('capabilities')
    op.drop_index(op.f('ix_time_windows_window_type'), table_name='time_windows')
    op.drop_index(op.f('ix_time_windows_state'), table_name='time_windows')
    op.drop_index(op.f('ix_time_windows_identity_id'), table_name='time_windows')
    op.drop_table('time_windows')
    op.drop_index(op.f('ix_identities_external_id'), table_name='identities')
    op.drop_table('identities')
    # ### end Alembic commands ###
