"""add notification tables

Revision ID: b63ec5f08081
Revises: be981e1dd668
Create Date: 2025-12-28 10:37:36.190436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b63ec5f08081'
down_revision: Union[str, None] = 'be981e1dd668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('identity_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_device_tokens_identity_active', 'device_tokens', ['identity_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_device_tokens_identity_id'), 'device_tokens', ['identity_id'], unique=False)
    op.create_index('ix_device_tokens_token', 'device_tokens', ['token'], unique=True)
    op.create_table('notification_preferences',
    sa.Column('identity_id', sa.String(length=36), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('in_app_enabled', sa.Boolean(), nullable=False),
    sa.Column('fasting_notifications', sa.Boolean(), nullable=False),
    sa.Column('workout_notifications', sa.Boolean(), nullable=False),
    sa.Column('streak_notifications', sa.Boolean(), nullable=False),
    sa.Column('achievement_notifications', sa.Boolean(), nullable=False),
    sa.Column('motivational_notifications', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_start', sa.Time(), nullable=True),
    sa.Column('quiet_hours_end', sa.Time(), nullable=True),
    sa.Column('daily_motivation_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('identity_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('identity_id', sa.String(length=36), nullable=False),
    sa.Column('notification_type', sa.Enum('PUSH', 'EMAIL', 'IN_APP', name='notificationtype'), nullable=False),
    sa.Column('category', sa.Enum('FASTING', 'WORKOUT', 'STREAK', 'ACHIEVEMENT', 'LEVEL_UP', 'REMINDER', 'MOTIVATIONAL', 'SYSTEM', name='notificationcategory'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='notificationpriority'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'DELIVERED', 'READ', 'FAILED', name='notificationstatus'), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_category'), 'notifications', ['category'], unique=False)
    op.create_index('ix_notifications_identity_created', 'notifications', ['identity_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_identity_id'), 'notifications', ['identity_id'], unique=False)
    op.create_index('ix_notifications_identity_status', 'notifications', ['identity_id', 'status'], unique=False)
    op.create_index('ix_notifications_scheduled', 'notifications', ['scheduled_for', 'status'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_table('scheduled_notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('identity_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.Enum('FASTING', 'WORKOUT', 'STREAK', 'ACHIEVEMENT', 'LEVEL_UP', 'REMINDER', 'MOTIVATIONAL', 'SYSTEM', name='notificationcategory'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('schedule_time', sa.Time(), nullable=False),
    sa.Column('schedule_days', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('next_trigger', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_notifications_identity_id'), 'scheduled_notifications', ['identity_id'], unique=False)
    op.create_index('ix_scheduled_notifications_next', 'scheduled_notifications', ['next_trigger', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scheduled_notifications_next', table_name='scheduled_notifications')
    op.drop_index(op.f('ix_scheduled_notifications_identity_id'), table_name='scheduled_notifications')
    op.drop_table('scheduled_notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index('ix_notifications_scheduled', table_name='notifications')
    op.drop_index('ix_notifications_identity_status', table_name='notifications')
    op.drop_index(op.f('ix_notifications_identity_id'), table_name='notifications')
    op.drop_index('ix_notifications_identity_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_category'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('notification_preferences')
    op.drop_index('ix_device_tokens_token', table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_identity_id'), table_name='device_tokens')
    op.drop_index('ix_device_tokens_identity_active', table_name='device_tokens')
    op.drop_table('device_tokens')
    # ### end Alembic commands ###
