"""add content tables

Revision ID: be981e1dd668
Revises: ef0543dddbb1
Create Date: 2025-12-28 10:07:02.453086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be981e1dd668'
down_revision: Union[str, None] = 'ef0543dddbb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('workouts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('workout_type', sa.Enum('HIIT', 'STRENGTH', 'CARDIO', 'FLEXIBILITY', 'RECOVERY', name='workouttype'), nullable=False),
    sa.Column('difficulty', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='difficultylevel'), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('calories_estimate', sa.Integer(), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('equipment_needed', sa.JSON(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('times_completed', sa.Integer(), nullable=False),
    sa.Column('total_rating', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['workout_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workouts_difficulty'), 'workouts', ['difficulty'], unique=False)
    op.create_index('ix_workouts_featured', 'workouts', ['is_featured'], unique=False)
    op.create_index('ix_workouts_type_difficulty', 'workouts', ['workout_type', 'difficulty'], unique=False)
    op.create_index(op.f('ix_workouts_workout_type'), 'workouts', ['workout_type'], unique=False)
    op.create_table('exercises',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workout_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('rest_seconds', sa.Integer(), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('calories_per_minute', sa.Float(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exercises_workout', 'exercises', ['workout_id'], unique=False)
    op.create_table('workout_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('identity_id', sa.String(length=36), nullable=False),
    sa.Column('workout_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'ABANDONED', name='sessionstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('calories_burned', sa.Integer(), nullable=True),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_sessions_identity_id'), 'workout_sessions', ['identity_id'], unique=False)
    op.create_index('ix_workout_sessions_identity_started', 'workout_sessions', ['identity_id', 'started_at'], unique=False)
    op.create_index('ix_workout_sessions_identity_status', 'workout_sessions', ['identity_id', 'status'], unique=False)
    op.create_index(op.f('ix_workout_sessions_status'), 'workout_sessions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_sessions_status'), table_name='workout_sessions')
    op.drop_index('ix_workout_sessions_identity_status', table_name='workout_sessions')
    op.drop_index('ix_workout_sessions_identity_started', table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_identity_id'), table_name='workout_sessions')
    op.drop_table('workout_sessions')
    op.drop_index('ix_exercises_workout', table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_workouts_workout_type'), table_name='workouts')
    op.drop_index('ix_workouts_type_difficulty', table_name='workouts')
    op.drop_index('ix_workouts_featured', table_name='workouts')
    op.drop_index(op.f('ix_workouts_difficulty'), table_name='workouts')
    op.drop_table('workouts')
    op.drop_table('workout_categories')
    # ### end Alembic commands ###
