"""add metrics table

Revision ID: ed45e0e5d74c
Revises: 376c6f80292d
Create Date: 2025-12-28 09:11:49.684165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed45e0e5d74c'
down_revision: Union[str, None] = '376c6f80292d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('identity_id', sa.String(length=36), nullable=False),
    sa.Column('metric_type', sa.Enum('WEIGHT_KG', 'WEIGHT_LBS', 'BODY_FAT_PCT', 'WATER_ML', 'CALORIES_CONSUMED', 'CALORIES_BURNED', 'STEPS', 'WORKOUT_MINUTES', 'FASTING_HOURS', 'SLEEP_HOURS', name='metrictype'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('USER_INPUT', 'CALCULATED', 'DEVICE_SYNC', name='metricsource'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_identity_id'), 'metrics', ['identity_id'], unique=False)
    op.create_index('ix_metrics_identity_type_timestamp', 'metrics', ['identity_id', 'metric_type', 'timestamp'], unique=False)
    op.create_index(op.f('ix_metrics_metric_type'), 'metrics', ['metric_type'], unique=False)
    op.create_index(op.f('ix_metrics_timestamp'), 'metrics', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrics_timestamp'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_metric_type'), table_name='metrics')
    op.drop_index('ix_metrics_identity_type_timestamp', table_name='metrics')
    op.drop_index(op.f('ix_metrics_identity_id'), table_name='metrics')
    op.drop_table('metrics')
    # ### end Alembic commands ###
