"""add progression tables

Revision ID: ef0543dddbb1
Revises: ed45e0e5d74c
Create Date: 2025-12-28 09:20:36.322403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef0543dddbb1'
down_revision: Union[str, None] = 'ed45e0e5d74c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('achievement_type', sa.Enum('STREAK', 'FASTING', 'WORKOUT', 'WEIGHT', 'SOCIAL', 'SPECIAL', name='achievementtype'), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('requirement_value', sa.Integer(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_achievement_type'), 'achievements', ['achievement_type'], unique=False)
    op.create_table('streaks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('identity_id', sa.String(length=36), nullable=False),
    sa.Column('streak_type', sa.Enum('FASTING', 'WORKOUT', 'LOGGING', 'APP_USAGE', name='streaktype'), nullable=False),
    sa.Column('current_count', sa.Integer(), nullable=False),
    sa.Column('longest_count', sa.Integer(), nullable=False),
    sa.Column('last_activity_date', sa.Date(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streaks_identity_id'), 'streaks', ['identity_id'], unique=False)
    op.create_index('ix_streaks_identity_type', 'streaks', ['identity_id', 'streak_type'], unique=True)
    op.create_table('user_achievements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('identity_id', sa.String(length=36), nullable=False),
    sa.Column('achievement_id', sa.String(length=36), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('is_unlocked', sa.Boolean(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_achievements_identity_achievement', 'user_achievements', ['identity_id', 'achievement_id'], unique=True)
    op.create_index(op.f('ix_user_achievements_identity_id'), 'user_achievements', ['identity_id'], unique=False)
    op.create_table('user_levels',
    sa.Column('identity_id', sa.String(length=36), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.Column('current_xp', sa.Integer(), nullable=False),
    sa.Column('total_xp_earned', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('identity_id')
    )
    op.create_table('xp_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('identity_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('FAST_COMPLETED', 'WORKOUT_COMPLETED', 'WEIGHT_LOGGED', 'STREAK_BONUS', 'ACHIEVEMENT_UNLOCKED', 'DAILY_LOGIN', 'LEVEL_UP_BONUS', name='xptransactiontype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('related_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_xp_transactions_identity_created', 'xp_transactions', ['identity_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_xp_transactions_identity_id'), 'xp_transactions', ['identity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_xp_transactions_identity_id'), table_name='xp_transactions')
    op.drop_index('ix_xp_transactions_identity_created', table_name='xp_transactions')
    op.drop_table('xp_transactions')
    op.drop_table('user_levels')
    op.drop_index(op.f('ix_user_achievements_identity_id'), table_name='user_achievements')
    op.drop_index('ix_user_achievements_identity_achievement', table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index('ix_streaks_identity_type', table_name='streaks')
    op.drop_index(op.f('ix_streaks_identity_id'), table_name='streaks')
    op.drop_table('streaks')
    op.drop_index(op.f('ix_achievements_achievement_type'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
