"""add profile tables

Revision ID: f14424e7a998
Revises: b63ec5f08081
Create Date: 2025-12-28 10:52:48.794284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f14424e7a998'
down_revision: Union[str, None] = 'b63ec5f08081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dietary_profiles',
    sa.Column('identity_id', sa.String(length=36), nullable=False),
    sa.Column('dietary_preference', sa.Enum('NONE', 'KETO', 'LOW_CARB', 'VEGAN', 'VEGETARIAN', 'PALEO', 'MEDITERRANEAN', 'WHOLE30', name='dietarypreference'), nullable=False),
    sa.Column('allergies', sa.JSON(), nullable=True),
    sa.Column('intolerances', sa.JSON(), nullable=True),
    sa.Column('calories_target', sa.Integer(), nullable=True),
    sa.Column('protein_target_g', sa.Integer(), nullable=True),
    sa.Column('carbs_target_g', sa.Integer(), nullable=True),
    sa.Column('fat_target_g', sa.Integer(), nullable=True),
    sa.Column('avoid_foods', sa.JSON(), nullable=True),
    sa.Column('favorite_foods', sa.JSON(), nullable=True),
    sa.Column('break_fast_preference', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('identity_id')
    )
    op.create_table('health_profiles',
    sa.Column('identity_id', sa.String(length=36), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('condition_notes', sa.Text(), nullable=True),
    sa.Column('takes_medication', sa.Boolean(), nullable=False),
    sa.Column('medication_notes', sa.Text(), nullable=True),
    sa.Column('medication_requires_food', sa.Boolean(), nullable=False),
    sa.Column('doctor_approved_fasting', sa.Boolean(), nullable=True),
    sa.Column('doctor_consultation_date', sa.Date(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('fasting_safe', sa.Boolean(), nullable=False),
    sa.Column('requires_medical_disclaimer', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('identity_id')
    )
    op.create_table('onboarding_status',
    sa.Column('identity_id', sa.String(length=36), nullable=False),
    sa.Column('basic_profile_completed', sa.Boolean(), nullable=False),
    sa.Column('goals_set', sa.Boolean(), nullable=False),
    sa.Column('health_profile_completed', sa.Boolean(), nullable=False),
    sa.Column('dietary_preferences_set', sa.Boolean(), nullable=False),
    sa.Column('workout_restrictions_set', sa.Boolean(), nullable=False),
    sa.Column('first_fast_completed', sa.Boolean(), nullable=False),
    sa.Column('first_workout_completed', sa.Boolean(), nullable=False),
    sa.Column('first_weight_logged', sa.Boolean(), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('skipped_steps', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('identity_id')
    )
    op.create_table('social_profiles',
    sa.Column('identity_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('friend_code', sa.String(length=8), nullable=False),
    sa.Column('profile_public', sa.Boolean(), nullable=False),
    sa.Column('show_streaks', sa.Boolean(), nullable=False),
    sa.Column('show_achievements', sa.Boolean(), nullable=False),
    sa.Column('show_level', sa.Boolean(), nullable=False),
    sa.Column('show_workouts', sa.Boolean(), nullable=False),
    sa.Column('show_weight', sa.Boolean(), nullable=False),
    sa.Column('friends_count', sa.Integer(), nullable=False),
    sa.Column('followers_count', sa.Integer(), nullable=False),
    sa.Column('following_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('identity_id')
    )
    op.create_index(op.f('ix_social_profiles_friend_code'), 'social_profiles', ['friend_code'], unique=True)
    op.create_index(op.f('ix_social_profiles_username'), 'social_profiles', ['username'], unique=True)
    op.create_table('user_goals',
    sa.Column('identity_id', sa.String(length=36), nullable=False),
    sa.Column('primary_goal', sa.Enum('WEIGHT_LOSS', 'WEIGHT_GAIN', 'MUSCLE_GAIN', 'MAINTAIN_WEIGHT', 'IMPROVE_FITNESS', 'INCREASE_ENERGY', 'BETTER_SLEEP', 'REDUCE_STRESS', name='goaltype'), nullable=False),
    sa.Column('secondary_goals', sa.JSON(), nullable=True),
    sa.Column('starting_weight_kg', sa.Float(), nullable=True),
    sa.Column('target_weight_kg', sa.Float(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('target_body_fat_percent', sa.Float(), nullable=True),
    sa.Column('target_muscle_mass_kg', sa.Float(), nullable=True),
    sa.Column('weekly_workout_goal', sa.Integer(), nullable=False),
    sa.Column('daily_step_goal', sa.Integer(), nullable=False),
    sa.Column('weekly_fasting_goal', sa.Integer(), nullable=False),
    sa.Column('target_fasting_hours', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('identity_id')
    )
    op.create_table('user_preferences',
    sa.Column('identity_id', sa.String(length=36), nullable=False),
    sa.Column('unit_system', sa.Enum('METRIC', 'IMPERIAL', name='unitsystem'), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('default_fasting_protocol', sa.Enum('SIXTEEN_EIGHT', 'EIGHTEEN_SIX', 'TWENTY_FOUR', 'CUSTOM', name='fastingprotocol'), nullable=False),
    sa.Column('custom_fast_hours', sa.Integer(), nullable=True),
    sa.Column('eating_window_start', sa.Time(), nullable=True),
    sa.Column('eating_window_end', sa.Time(), nullable=True),
    sa.Column('preferred_workout_time', sa.Time(), nullable=True),
    sa.Column('workout_reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('preferred_workout_types', sa.JSON(), nullable=True),
    sa.Column('dark_mode', sa.Boolean(), nullable=False),
    sa.Column('haptic_feedback', sa.Boolean(), nullable=False),
    sa.Column('sound_effects', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('identity_id')
    )
    op.create_table('user_profiles',
    sa.Column('identity_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY', name='gender'), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('identity_id')
    )
    op.create_index(op.f('ix_user_profiles_email'), 'user_profiles', ['email'], unique=False)
    op.create_table('workout_restrictions',
    sa.Column('identity_id', sa.String(length=36), nullable=False),
    sa.Column('injury_areas', sa.JSON(), nullable=True),
    sa.Column('injury_notes', sa.Text(), nullable=True),
    sa.Column('has_chronic_pain', sa.Boolean(), nullable=False),
    sa.Column('chronic_pain_areas', sa.JSON(), nullable=True),
    sa.Column('avoid_high_impact', sa.Boolean(), nullable=False),
    sa.Column('avoid_jumping', sa.Boolean(), nullable=False),
    sa.Column('avoid_heavy_weights', sa.Boolean(), nullable=False),
    sa.Column('avoid_floor_exercises', sa.Boolean(), nullable=False),
    sa.Column('fitness_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='fitnesslevel'), nullable=False),
    sa.Column('max_workout_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('has_gym_access', sa.Boolean(), nullable=False),
    sa.Column('home_equipment', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('identity_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_restrictions')
    op.drop_index(op.f('ix_user_profiles_email'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_table('user_preferences')
    op.drop_table('user_goals')
    op.drop_index(op.f('ix_social_profiles_username'), table_name='social_profiles')
    op.drop_index(op.f('ix_social_profiles_friend_code'), table_name='social_profiles')
    op.drop_table('social_profiles')
    op.drop_table('onboarding_status')
    op.drop_table('health_profiles')
    op.drop_table('dietary_profiles')
    # ### end Alembic commands ###
