"""Seed 42 recipes with nutritional data for UGOKI app."""

import asyncio
import uuid
from datetime import datetime, UTC

from sqlalchemy import select
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
from sqlalchemy.orm import sessionmaker

from src.modules.content.orm import RecipeORM
from src.modules.content.models import MealType, DietTag
from src.core.config import settings


DATABASE_URL = str(settings.database_url)

# 42 curated recipes for fitness-focused users
RECIPES = [
    # ============ BREAKFAST (10 recipes) ============
    {
        "name": "Greek Yogurt Protein Bowl",
        "description": "Creamy Greek yogurt topped with berries, granola, and honey. Perfect post-workout breakfast.",
        "meal_type": MealType.BREAKFAST,
        "prep_time_minutes": 5,
        "cook_time_minutes": 0,
        "servings": 1,
        "calories": 350,
        "protein_g": 25,
        "carbs_g": 42,
        "fat_g": 8,
        "fiber_g": 4,
        "sugar_g": 28,
        "ingredients": [
            {"name": "Greek yogurt (0% fat)", "amount": "1 cup (200g)", "notes": None},
            {"name": "Mixed berries", "amount": "1/2 cup", "notes": "fresh or frozen"},
            {"name": "Granola", "amount": "1/4 cup", "notes": "low sugar"},
            {"name": "Honey", "amount": "1 tbsp", "notes": None},
            {"name": "Chia seeds", "amount": "1 tsp", "notes": "optional"},
        ],
        "instructions": [
            "Add Greek yogurt to a bowl.",
            "Top with mixed berries.",
            "Sprinkle granola over the top.",
            "Drizzle with honey and chia seeds.",
            "Serve immediately.",
        ],
        "diet_tags": [DietTag.HIGH_PROTEIN, DietTag.VEGETARIAN, DietTag.QUICK],
        "is_featured": True,
    },
    {
        "name": "Egg White Veggie Omelette",
        "description": "Fluffy egg white omelette packed with vegetables. Low calorie, high protein breakfast.",
        "meal_type": MealType.BREAKFAST,
        "prep_time_minutes": 10,
        "cook_time_minutes": 8,
        "servings": 1,
        "calories": 180,
        "protein_g": 22,
        "carbs_g": 8,
        "fat_g": 6,
        "fiber_g": 2,
        "sugar_g": 4,
        "ingredients": [
            {"name": "Egg whites", "amount": "5 large", "notes": None},
            {"name": "Spinach", "amount": "1 cup", "notes": "fresh"},
            {"name": "Bell pepper", "amount": "1/4 cup", "notes": "diced"},
            {"name": "Mushrooms", "amount": "1/4 cup", "notes": "sliced"},
            {"name": "Olive oil spray", "amount": "1 spray", "notes": None},
            {"name": "Salt and pepper", "amount": "to taste", "notes": None},
        ],
        "instructions": [
            "Heat a non-stick pan over medium heat with olive oil spray.",
            "Sauté vegetables until softened, about 3 minutes.",
            "Remove vegetables and set aside.",
            "Pour egg whites into pan and cook until edges set.",
            "Add vegetables to one half of the omelette.",
            "Fold omelette in half and cook 1 more minute.",
            "Season with salt and pepper.",
        ],
        "diet_tags": [DietTag.HIGH_PROTEIN, DietTag.LOW_CARB, DietTag.VEGETARIAN, DietTag.QUICK],
        "is_featured": False,
    },
    {
        "name": "Overnight Protein Oats",
        "description": "Prep the night before for a grab-and-go breakfast. Creamy oats with 30g protein.",
        "meal_type": MealType.BREAKFAST,
        "prep_time_minutes": 5,
        "cook_time_minutes": 0,
        "servings": 1,
        "calories": 420,
        "protein_g": 30,
        "carbs_g": 52,
        "fat_g": 10,
        "fiber_g": 7,
        "sugar_g": 12,
        "ingredients": [
            {"name": "Rolled oats", "amount": "1/2 cup", "notes": None},
            {"name": "Protein powder", "amount": "1 scoop (25g)", "notes": "vanilla or chocolate"},
            {"name": "Almond milk", "amount": "3/4 cup", "notes": "unsweetened"},
            {"name": "Greek yogurt", "amount": "1/4 cup", "notes": None},
            {"name": "Chia seeds", "amount": "1 tbsp", "notes": None},
            {"name": "Banana", "amount": "1/2", "notes": "sliced"},
        ],
        "instructions": [
            "Mix oats, protein powder, almond milk, yogurt, and chia seeds in a jar.",
            "Stir well to combine and eliminate lumps.",
            "Cover and refrigerate overnight (at least 6 hours).",
            "In the morning, top with sliced banana.",
            "Enjoy cold or microwave for 1-2 minutes if preferred warm.",
        ],
        "diet_tags": [DietTag.HIGH_PROTEIN, DietTag.VEGETARIAN, DietTag.MEAL_PREP],
        "is_featured": True,
    },
    {
        "name": "Avocado Toast with Eggs",
        "description": "Classic avocado toast elevated with poached eggs and everything bagel seasoning.",
        "meal_type": MealType.BREAKFAST,
        "prep_time_minutes": 5,
        "cook_time_minutes": 10,
        "servings": 1,
        "calories": 380,
        "protein_g": 18,
        "carbs_g": 28,
        "fat_g": 22,
        "fiber_g": 8,
        "sugar_g": 3,
        "ingredients": [
            {"name": "Whole grain bread", "amount": "2 slices", "notes": None},
            {"name": "Avocado", "amount": "1/2 medium", "notes": "ripe"},
            {"name": "Eggs", "amount": "2 large", "notes": None},
            {"name": "Everything bagel seasoning", "amount": "1 tsp", "notes": None},
            {"name": "Red pepper flakes", "amount": "pinch", "notes": "optional"},
            {"name": "Lemon juice", "amount": "1 tsp", "notes": None},
        ],
        "instructions": [
            "Toast bread until golden brown.",
            "Mash avocado with lemon juice, salt, and pepper.",
            "Poach or fry eggs to your preference.",
            "Spread mashed avocado on toast.",
            "Top with eggs and everything bagel seasoning.",
            "Add red pepper flakes if desired.",
        ],
        "diet_tags": [DietTag.HIGH_PROTEIN, DietTag.VEGETARIAN],
        "is_featured": False,
    },
    {
        "name": "Protein Pancakes",
        "description": "Fluffy pancakes made with protein powder and oats. 35g protein per serving!",
        "meal_type": MealType.BREAKFAST,
        "prep_time_minutes": 5,
        "cook_time_minutes": 10,
        "servings": 1,
        "calories": 380,
        "protein_g": 35,
        "carbs_g": 40,
        "fat_g": 8,
        "fiber_g": 5,
        "sugar_g": 8,
        "ingredients": [
            {"name": "Oat flour", "amount": "1/2 cup", "notes": "or blended oats"},
            {"name": "Protein powder", "amount": "1 scoop", "notes": "vanilla"},
            {"name": "Egg whites", "amount": "3 large", "notes": None},
            {"name": "Baking powder", "amount": "1/2 tsp", "notes": None},
            {"name": "Almond milk", "amount": "1/4 cup", "notes": None},
            {"name": "Maple syrup", "amount": "1 tbsp", "notes": "for serving"},
        ],
        "instructions": [
            "Mix oat flour, protein powder, and baking powder.",
            "Add egg whites and almond milk, whisk until smooth.",
            "Heat non-stick pan over medium heat.",
            "Pour 1/4 cup batter per pancake.",
            "Cook until bubbles form, then flip.",
            "Serve with maple syrup.",
        ],
        "diet_tags": [DietTag.HIGH_PROTEIN, DietTag.VEGETARIAN, DietTag.POST_WORKOUT],
        "is_featured": True,
    },
    {
        "name": "Breakfast Burrito Bowl",
        "description": "Deconstructed breakfast burrito with scrambled eggs, black beans, and salsa.",
        "meal_type": MealType.BREAKFAST,
        "prep_time_minutes": 10,
        "cook_time_minutes": 10,
        "servings": 1,
        "calories": 450,
        "protein_g": 28,
        "carbs_g": 45,
        "fat_g": 16,
        "fiber_g": 10,
        "sugar_g": 5,
        "ingredients": [
            {"name": "Eggs", "amount": "3 large", "notes": None},
            {"name": "Black beans", "amount": "1/2 cup", "notes": "canned, drained"},
            {"name": "Brown rice", "amount": "1/2 cup", "notes": "cooked"},
            {"name": "Salsa", "amount": "3 tbsp", "notes": None},
            {"name": "Cheese", "amount": "2 tbsp", "notes": "shredded, optional"},
            {"name": "Avocado", "amount": "1/4", "notes": "sliced"},
        ],
        "instructions": [
            "Scramble eggs in a pan until fluffy.",
            "Heat black beans in microwave or pan.",
            "Layer rice in a bowl.",
            "Add scrambled eggs and black beans.",
            "Top with salsa, cheese, and avocado.",
        ],
        "diet_tags": [DietTag.HIGH_PROTEIN, DietTag.VEGETARIAN, DietTag.GLUTEN_FREE],
        "is_featured": False,
    },
    {
        "name": "Cottage Cheese Fruit Bowl",
        "description": "Simple high-protein breakfast with cottage cheese and fresh fruit.",
        "meal_type": MealType.BREAKFAST,
        "prep_time_minutes": 3,
        "cook_time_minutes": 0,
        "servings": 1,
        "calories": 280,
        "protein_g": 28,
        "carbs_g": 30,
        "fat_g": 4,
        "fiber_g": 3,
        "sugar_g": 22,
        "ingredients": [
            {"name": "Cottage cheese (1% fat)", "amount": "1 cup", "notes": None},
            {"name": "Pineapple chunks", "amount": "1/2 cup", "notes": "fresh or canned"},
            {"name": "Blueberries", "amount": "1/4 cup", "notes": None},
            {"name": "Sliced almonds", "amount": "1 tbsp", "notes": None},
        ],
        "instructions": [
            "Add cottage cheese to a bowl.",
            "Top with pineapple and blueberries.",
            "Sprinkle with sliced almonds.",
            "Enjoy immediately.",
        ],
        "diet_tags": [DietTag.HIGH_PROTEIN, DietTag.LOW_CARB, DietTag.VEGETARIAN, DietTag.QUICK],
        "is_featured": False,
    },
    {
        "name": "Smoked Salmon Bagel Thin",
        "description": "Light version of the classic lox bagel with cream cheese and capers.",
        "meal_type": MealType.BREAKFAST,
        "prep_time_minutes": 5,
        "cook_time_minutes": 0,
        "servings": 1,
        "calories": 320,
        "protein_g": 22,
        "carbs_g": 28,
        "fat_g": 14,
        "fiber_g": 3,
        "sugar_g": 4,
        "ingredients": [
            {"name": "Whole wheat bagel thin", "amount": "1", "notes": None},
            {"name": "Smoked salmon", "amount": "3 oz", "notes": None},
            {"name": "Light cream cheese", "amount": "2 tbsp", "notes": None},
            {"name": "Red onion", "amount": "2 slices", "notes": "thin"},
            {"name": "Capers", "amount": "1 tsp", "notes": None},
            {"name": "Fresh dill", "amount": "to taste", "notes": None},
        ],
        "instructions": [
            "Toast bagel thin until lightly browned.",
            "Spread cream cheese on both halves.",
            "Layer smoked salmon on top.",
            "Add red onion slices and capers.",
            "Garnish with fresh dill.",
        ],
        "diet_tags": [DietTag.HIGH_PROTEIN, DietTag.QUICK, DietTag.MEDITERRANEAN],
        "is_featured": False,
    },
    {
        "name": "Banana Almond Smoothie",
        "description": "Creamy, filling smoothie with banana, almond butter, and protein powder.",
        "meal_type": MealType.BREAKFAST,
        "prep_time_minutes": 5,
        "cook_time_minutes": 0,
        "servings": 1,
        "calories": 400,
        "protein_g": 32,
        "carbs_g": 45,
        "fat_g": 12,
        "fiber_g": 5,
        "sugar_g": 22,
        "ingredients": [
            {"name": "Banana", "amount": "1 medium", "notes": "frozen preferred"},
            {"name": "Protein powder", "amount": "1 scoop", "notes": "vanilla"},
            {"name": "Almond butter", "amount": "1 tbsp", "notes": None},
            {"name": "Almond milk", "amount": "1 cup", "notes": "unsweetened"},
            {"name": "Spinach", "amount": "handful", "notes": "optional"},
            {"name": "Ice", "amount": "4-5 cubes", "notes": None},
        ],
        "instructions": [
            "Add all ingredients to a blender.",
            "Blend on high until smooth and creamy.",
            "Add more milk if too thick.",
            "Pour into a glass and serve immediately.",
        ],
        "diet_tags": [DietTag.HIGH_PROTEIN, DietTag.VEGETARIAN, DietTag.QUICK, DietTag.POST_WORKOUT],
        "is_featured": False,
    },
    {
        "name": "Turkey Sausage Egg Muffins",
        "description": "Meal prep friendly egg muffins with turkey sausage and vegetables. Make 12 for the week!",
        "meal_type": MealType.BREAKFAST,
        "prep_time_minutes": 15,
        "cook_time_minutes": 25,
        "servings": 4,
        "calories": 180,
        "protein_g": 18,
        "carbs_g": 4,
        "fat_g": 10,
        "fiber_g": 1,
        "sugar_g": 2,
        "ingredients": [
            {"name": "Eggs", "amount": "8 large", "notes": None},
            {"name": "Turkey sausage", "amount": "8 oz", "notes": "crumbled"},
            {"name": "Bell peppers", "amount": "1/2 cup", "notes": "diced"},
            {"name": "Spinach", "amount": "1 cup", "notes": "chopped"},
            {"name": "Cheese", "amount": "1/2 cup", "notes": "shredded"},
            {"name": "Salt and pepper", "amount": "to taste", "notes": None},
        ],
        "instructions": [
            "Preheat oven to 350°F (175°C).",
            "Brown turkey sausage in a pan, drain excess fat.",
            "Whisk eggs with salt and pepper.",
            "Divide sausage, peppers, and spinach into greased muffin tin.",
            "Pour egg mixture over filling.",
            "Top with cheese.",
            "Bake 20-25 minutes until eggs are set.",
            "Store in fridge for up to 5 days.",
        ],
        "diet_tags": [DietTag.HIGH_PROTEIN, DietTag.LOW_CARB, DietTag.KETO, DietTag.MEAL_PREP, DietTag.GLUTEN_FREE],
        "is_featured": True,
    },

    # ============ LUNCH (10 recipes) ============
    {
        "name": "Grilled Chicken Caesar Salad",
        "description": "Classic Caesar salad with grilled chicken breast. Restaurant quality at home.",
        "meal_type": MealType.LUNCH,
        "prep_time_minutes": 15,
        "cook_time_minutes": 15,
        "servings": 1,
        "calories": 420,
        "protein_g": 42,
        "carbs_g": 18,
        "fat_g": 20,
        "fiber_g": 4,
        "sugar_g": 4,
        "ingredients": [
            {"name": "Chicken breast", "amount": "6 oz", "notes": None},
            {"name": "Romaine lettuce", "amount": "3 cups", "notes": "chopped"},
            {"name": "Parmesan cheese", "amount": "2 tbsp", "notes": "shaved"},
            {"name": "Caesar dressing", "amount": "2 tbsp", "notes": "light"},
            {"name": "Croutons", "amount": "1/4 cup", "notes": "whole wheat"},
            {"name": "Lemon juice", "amount": "1 tbsp", "notes": None},
        ],
        "instructions": [
            "Season chicken with salt, pepper, and lemon juice.",
            "Grill chicken 6-7 minutes per side until cooked through.",
            "Let chicken rest 5 minutes, then slice.",
            "Toss romaine with Caesar dressing.",
            "Top with sliced chicken, parmesan, and croutons.",
        ],
        "diet_tags": [DietTag.HIGH_PROTEIN, DietTag.LOW_CARB],
        "is_featured": True,
    },
    {
        "name": "Turkey & Avocado Wrap",
        "description": "Protein-packed wrap with lean turkey, avocado, and crunchy vegetables.",
        "meal_type": MealType.LUNCH,
        "prep_time_minutes": 10,
        "cook_time_minutes": 0,
        "servings": 1,
        "calories": 380,
        "protein_g": 28,
        "carbs_g": 32,
        "fat_g": 16,
        "fiber_g": 8,
        "sugar_g": 4,
        "ingredients": [
            {"name": "Whole wheat tortilla", "amount": "1 large (10\")", "notes": None},
            {"name": "Sliced turkey breast", "amount": "4 oz", "notes": "low sodium"},
            {"name": "Avocado", "amount": "1/3", "notes": "sliced"},
            {"name": "Lettuce", "amount": "1/2 cup", "notes": None},
            {"name": "Tomato", "amount": "3 slices", "notes": None},
            {"name": "Mustard", "amount": "1 tbsp", "notes": None},
        ],
        "instructions": [
            "Lay tortilla flat and spread mustard.",
            "Layer turkey down the center.",
            "Add avocado slices, lettuce, and tomato.",
            "Fold sides in, then roll tightly.",
            "Cut in half diagonally to serve.",
        ],
        "diet_tags": [DietTag.HIGH_PROTEIN, DietTag.QUICK],
        "is_featured": False,
    },
    {
        "name": "Quinoa Buddha Bowl",
        "description": "Colorful plant-based bowl with quinoa, roasted chickpeas, and tahini dressing.",
        "meal_type": MealType.LUNCH,
        "prep_time_minutes": 15,
        "cook_time_minutes": 25,
        "servings": 1,
        "calories": 480,
        "protein_g": 18,
        "carbs_g": 62,
        "fat_g": 18,
        "fiber_g": 14,
        "sugar_g": 8,
        "ingredients": [
            {"name": "Quinoa", "amount": "1/2 cup", "notes": "dry"},
            {"name": "Chickpeas", "amount": "1/2 cup", "notes": "canned, drained"},
            {"name": "Sweet potato", "amount": "1/2 medium", "notes": "cubed"},
            {"name": "Kale", "amount": "1 cup", "notes": "chopped"},
            {"name": "Tahini", "amount": "2 tbsp", "notes": None},
            {"name": "Lemon juice", "amount": "1 tbsp", "notes": None},
            {"name": "Olive oil", "amount": "1 tbsp", "notes": None},
        ],
        "instructions": [
            "Cook quinoa according to package directions.",
            "Preheat oven to 400°F (200°C).",
            "Toss chickpeas and sweet potato with olive oil, roast 20-25 minutes.",
            "Massage kale with a little lemon juice.",
            "Mix tahini with lemon juice and water for dressing.",
            "Assemble bowl with quinoa, roasted vegetables, and kale.",
            "Drizzle with tahini dressing.",
        ],
        "diet_tags": [DietTag.VEGAN, DietTag.HIGH_PROTEIN, DietTag.GLUTEN_FREE, DietTag.MEDITERRANEAN],
        "is_featured": True,
    },
    {
        "name": "Tuna Salad Lettuce Wraps",
        "description": "Low-carb tuna salad served in crisp lettuce cups. Perfect for keto.",
        "meal_type": MealType.LUNCH,
        "prep_time_minutes": 10,
        "cook_time_minutes": 0,
        "servings": 1,
        "calories": 280,
        "protein_g": 32,
        "carbs_g": 8,
        "fat_g": 14,
        "fiber_g": 2,
        "sugar_g": 4,
        "ingredients": [
            {"name": "Canned tuna", "amount": "5 oz", "notes": "drained"},
            {"name": "Greek yogurt", "amount": "2 tbsp", "notes": "plain"},
            {"name": "Celery", "amount": "2 tbsp", "notes": "diced"},
            {"name": "Red onion", "amount": "1 tbsp", "notes": "diced"},
            {"name": "Butter lettuce", "amount": "4 large leaves", "notes": None},
            {"name": "Dijon mustard", "amount": "1 tsp", "notes": None},
        ],
        "instructions": [
            "Mix tuna, Greek yogurt, mustard, celery, and onion.",
            "Season with salt and pepper.",
            "Divide tuna mixture among lettuce cups.",
            "Serve immediately.",
        ],
        "diet_tags": [DietTag.HIGH_PROTEIN, DietTag.LOW_CARB, DietTag.KETO, DietTag.QUICK, DietTag.GLUTEN_FREE],
        "is_featured": False,
    },
    {
        "name": "Asian Chicken Salad",
        "description": "Crunchy salad with sesame-ginger dressing and edamame. Fresh and satisfying.",
        "meal_type": MealType.LUNCH,
        "prep_time_minutes": 15,
        "cook_time_minutes": 0,
        "servings": 1,
        "calories": 380,
        "protein_g": 35,
        "carbs_g": 28,
        "fat_g": 14,
        "fiber_g": 6,
        "sugar_g": 10,
        "ingredients": [
            {"name": "Cooked chicken breast", "amount": "5 oz", "notes": "shredded"},
            {"name": "Mixed greens", "amount": "2 cups", "notes": None},
            {"name": "Edamame", "amount": "1/4 cup", "notes": "shelled"},
            {"name": "Mandarin oranges", "amount": "1/4 cup", "notes": None},
            {"name": "Sliced almonds", "amount": "1 tbsp", "notes": None},
            {"name": "Sesame ginger dressing", "amount": "2 tbsp", "notes": None},
            {"name": "Crispy wonton strips", "amount": "2 tbsp", "notes": None},
        ],
        "instructions": [
            "Combine greens, chicken, edamame, and oranges in a bowl.",
            "Top with almonds and wonton strips.",
            "Drizzle with sesame ginger dressing.",
            "Toss gently and serve.",
        ],
        "diet_tags": [DietTag.HIGH_PROTEIN, DietTag.QUICK],
        "is_featured": False,
    },
    {
        "name": "Mediterranean Chicken Pita",
        "description": "Grilled chicken pita with hummus, feta, and fresh vegetables.",
        "meal_type": MealType.LUNCH,
        "prep_time_minutes": 10,
        "cook_time_minutes": 10,
        "servings": 1,
        "calories": 440,
        "protein_g": 38,
        "carbs_g": 38,
        "fat_g": 14,
        "fiber_g": 6,
        "sugar_g": 5,
        "ingredients": [
            {"name": "Whole wheat pita", "amount": "1 large", "notes": None},
            {"name": "Chicken breast", "amount": "5 oz", "notes": "grilled, sliced"},
            {"name": "Hummus", "amount": "3 tbsp", "notes": None},
            {"name": "Cucumber", "amount": "1/4 cup", "notes": "diced"},
            {"name": "Tomatoes", "amount": "1/4 cup", "notes": "diced"},
            {"name": "Feta cheese", "amount": "2 tbsp", "notes": "crumbled"},
            {"name": "Red onion", "amount": "2 tbsp", "notes": "sliced"},
        ],
        "instructions": [
            "Warm pita briefly in microwave or pan.",
            "Spread hummus inside pita pocket.",
            "Fill with grilled chicken.",
            "Add cucumber, tomatoes, onion, and feta.",
            "Serve immediately.",
        ],
        "diet_tags": [DietTag.HIGH_PROTEIN, DietTag.MEDITERRANEAN],
        "is_featured": True,
    },
    {
        "name": "Shrimp Avocado Salad",
        "description": "Light and refreshing salad with grilled shrimp and creamy avocado.",
        "meal_type": MealType.LUNCH,
        "prep_time_minutes": 15,
        "cook_time_minutes": 8,
        "servings": 1,
        "calories": 350,
        "protein_g": 32,
        "carbs_g": 14,
        "fat_g": 20,
        "fiber_g": 8,
        "sugar_g": 4,
        "ingredients": [
            {"name": "Large shrimp", "amount": "6 oz", "notes": "peeled"},
            {"name": "Mixed greens", "amount": "3 cups", "notes": None},
            {"name": "Avocado", "amount": "1/2", "notes": "sliced"},
            {"name": "Cherry tomatoes", "amount": "1/2 cup", "notes": "halved"},
            {"name": "Olive oil", "amount": "1 tbsp", "notes": None},
            {"name": "Lime juice", "amount": "1 tbsp", "notes": None},
            {"name": "Cilantro", "amount": "2 tbsp", "notes": "chopped"},
        ],
        "instructions": [
            "Season shrimp with salt, pepper, and half the lime juice.",
            "Grill or sauté shrimp 2-3 minutes per side.",
            "Arrange greens on a plate.",
            "Top with shrimp, avocado, and tomatoes.",
            "Drizzle with olive oil and remaining lime juice.",
            "Garnish with cilantro.",
        ],
        "diet_tags": [DietTag.HIGH_PROTEIN, DietTag.LOW_CARB, DietTag.KETO, DietTag.GLUTEN_FREE, DietTag.PALEO],
        "is_featured": False,
    },
    {
        "name": "Greek Chicken Bowl",
        "description": "Meal prep bowl with grilled chicken, rice, and Greek salad fixings.",
        "meal_type": MealType.LUNCH,
        "prep_time_minutes": 15,
        "cook_time_minutes": 20,
        "servings": 1,
        "calories": 520,
        "protein_g": 45,
        "carbs_g": 42,
        "fat_g": 18,
        "fiber_g": 5,
        "sugar_g": 6,
        "ingredients": [
            {"name": "Chicken thigh", "amount": "6 oz", "notes": "boneless"},
            {"name": "Brown rice", "amount": "1/2 cup", "notes": "cooked"},
            {"name": "Cucumber", "amount": "1/2 cup", "notes": "diced"},
            {"name": "Cherry tomatoes", "amount": "1/2 cup", "notes": "halved"},
            {"name": "Kalamata olives", "amount": "6", "notes": None},
            {"name": "Feta cheese", "amount": "2 tbsp", "notes": None},
            {"name": "Tzatziki", "amount": "3 tbsp", "notes": None},
            {"name": "Dried oregano", "amount": "1 tsp", "notes": None},
        ],
        "instructions": [
            "Season chicken with oregano, salt, and pepper.",
            "Grill or pan-cook chicken until done, about 6-7 minutes per side.",
            "Let rest, then slice.",
            "Build bowl with rice as base.",
            "Add cucumber, tomatoes, and olives.",
            "Top with sliced chicken and feta.",
            "Drizzle with tzatziki.",
        ],
        "diet_tags": [DietTag.HIGH_PROTEIN, DietTag.MEDITERRANEAN, DietTag.MEAL_PREP, DietTag.GLUTEN_FREE],
        "is_featured": False,
    },
    {
        "name": "Beef & Broccoli Stir-Fry",
        "description": "Quick and easy stir-fry with lean beef and crisp broccoli in garlic sauce.",
        "meal_type": MealType.LUNCH,
        "prep_time_minutes": 15,
        "cook_time_minutes": 15,
        "servings": 2,
        "calories": 340,
        "protein_g": 32,
        "carbs_g": 18,
        "fat_g": 16,
        "fiber_g": 4,
        "sugar_g": 8,
        "ingredients": [
            {"name": "Lean beef sirloin", "amount": "8 oz", "notes": "sliced thin"},
            {"name": "Broccoli florets", "amount": "3 cups", "notes": None},
            {"name": "Garlic", "amount": "3 cloves", "notes": "minced"},
            {"name": "Low sodium soy sauce", "amount": "2 tbsp", "notes": None},
            {"name": "Sesame oil", "amount": "1 tbsp", "notes": None},
            {"name": "Ginger", "amount": "1 tsp", "notes": "minced"},
            {"name": "Cornstarch", "amount": "1 tsp", "notes": None},
        ],
        "instructions": [
            "Mix soy sauce, sesame oil, ginger, and cornstarch for sauce.",
            "Heat pan or wok over high heat.",
            "Stir-fry beef until browned, 2-3 minutes. Remove.",
            "Add broccoli and garlic, stir-fry 4-5 minutes.",
            "Return beef to pan.",
            "Pour sauce over and toss to coat.",
            "Serve over rice or cauliflower rice.",
        ],
        "diet_tags": [DietTag.HIGH_PROTEIN, DietTag.LOW_CARB, DietTag.QUICK, DietTag.DAIRY_FREE],
        "is_featured": False,
    },
    {
        "name": "Chickpea Curry Bowl",
        "description": "Plant-based curry with chickpeas and spinach. Warming and satisfying.",
        "meal_type": MealType.LUNCH,
        "prep_time_minutes": 10,
        "cook_time_minutes": 20,
        "servings": 2,
        "calories": 380,
        "protein_g": 14,
        "carbs_g": 52,
        "fat_g": 14,
        "fiber_g": 12,
        "sugar_g": 10,
        "ingredients": [
            {"name": "Chickpeas", "amount": "1 can (15 oz)", "notes": "drained"},
            {"name": "Coconut milk", "amount": "1/2 can", "notes": "light"},
            {"name": "Spinach", "amount": "2 cups", "notes": None},
            {"name": "Onion", "amount": "1/2", "notes": "diced"},
            {"name": "Curry powder", "amount": "2 tbsp", "notes": None},
            {"name": "Garlic", "amount": "2 cloves", "notes": "minced"},
            {"name": "Diced tomatoes", "amount": "1/2 can", "notes": None},
            {"name": "Basmati rice", "amount": "1 cup", "notes": "cooked"},
        ],
        "instructions": [
            "Sauté onion and garlic until softened.",
            "Add curry powder, stir 1 minute.",
            "Add chickpeas, tomatoes, and coconut milk.",
            "Simmer 15 minutes.",
            "Stir in spinach until wilted.",
            "Serve over basmati rice.",
        ],
        "diet_tags": [DietTag.VEGAN, DietTag.VEGETARIAN, DietTag.DAIRY_FREE, DietTag.GLUTEN_FREE],
        "is_featured": False,
    },

    # ============ DINNER (10 recipes) ============
    {
        "name": "Grilled Salmon with Asparagus",
        "description": "Omega-3 rich salmon with roasted asparagus and lemon butter.",
        "meal_type": MealType.DINNER,
        "prep_time_minutes": 10,
        "cook_time_minutes": 20,
        "servings": 1,
        "calories": 450,
        "protein_g": 42,
        "carbs_g": 12,
        "fat_g": 26,
        "fiber_g": 5,
        "sugar_g": 4,
        "ingredients": [
            {"name": "Salmon fillet", "amount": "6 oz", "notes": None},
            {"name": "Asparagus", "amount": "1 bunch", "notes": "trimmed"},
            {"name": "Olive oil", "amount": "1 tbsp", "notes": None},
            {"name": "Butter", "amount": "1 tbsp", "notes": None},
            {"name": "Lemon", "amount": "1/2", "notes": None},
            {"name": "Garlic", "amount": "2 cloves", "notes": "minced"},
            {"name": "Fresh dill", "amount": "1 tbsp", "notes": "chopped"},
        ],
        "instructions": [
            "Preheat oven to 400°F (200°C).",
            "Toss asparagus with olive oil, salt, and pepper.",
            "Roast asparagus 15 minutes.",
            "Season salmon with salt, pepper, and garlic.",
            "Pan-sear salmon 4 minutes per side.",
            "Top with butter, lemon juice, and dill.",
            "Serve with roasted asparagus.",
        ],
        "diet_tags": [DietTag.HIGH_PROTEIN, DietTag.LOW_CARB, DietTag.KETO, DietTag.GLUTEN_FREE, DietTag.PALEO],
        "is_featured": True,
    },
    {
        "name": "Turkey Meatballs with Zucchini Noodles",
        "description": "Lean turkey meatballs in marinara sauce served over zucchini noodles.",
        "meal_type": MealType.DINNER,
        "prep_time_minutes": 20,
        "cook_time_minutes": 25,
        "servings": 2,
        "calories": 380,
        "protein_g": 38,
        "carbs_g": 18,
        "fat_g": 16,
        "fiber_g": 4,
        "sugar_g": 10,
        "ingredients": [
            {"name": "Ground turkey", "amount": "1 lb", "notes": "93% lean"},
            {"name": "Egg", "amount": "1", "notes": None},
            {"name": "Breadcrumbs", "amount": "1/4 cup", "notes": "whole wheat"},
            {"name": "Italian seasoning", "amount": "1 tsp", "notes": None},
            {"name": "Marinara sauce", "amount": "1 cup", "notes": "low sugar"},
            {"name": "Zucchini", "amount": "3 medium", "notes": "spiralized"},
            {"name": "Parmesan", "amount": "2 tbsp", "notes": "grated"},
        ],
        "instructions": [
            "Mix turkey, egg, breadcrumbs, and seasoning.",
            "Form into 12 meatballs.",
            "Bake at 400°F for 20 minutes.",
            "Heat marinara sauce in a pan.",
            "Add meatballs to sauce, simmer 5 minutes.",
            "Sauté zucchini noodles 2-3 minutes.",
            "Serve meatballs over zoodles with parmesan.",
        ],
        "diet_tags": [DietTag.HIGH_PROTEIN, DietTag.LOW_CARB],
        "is_featured": True,
    },
    {
        "name": "Baked Lemon Herb Chicken",
        "description": "Juicy bone-in chicken thighs with herbs and roasted vegetables.",
        "meal_type": MealType.DINNER,
        "prep_time_minutes": 15,
        "cook_time_minutes": 45,
        "servings": 2,
        "calories": 420,
        "protein_g": 38,
        "carbs_g": 22,
        "fat_g": 20,
        "fiber_g": 5,
        "sugar_g": 6,
        "ingredients": [
            {"name": "Chicken thighs", "amount": "4 pieces", "notes": "bone-in, skin-on"},
            {"name": "Potatoes", "amount": "1 lb", "notes": "baby, halved"},
            {"name": "Green beans", "amount": "1 cup", "notes": "trimmed"},
            {"name": "Olive oil", "amount": "2 tbsp", "notes": None},
            {"name": "Lemon", "amount": "1", "notes": "sliced"},
            {"name": "Rosemary", "amount": "2 sprigs", "notes": "fresh"},
            {"name": "Thyme", "amount": "4 sprigs", "notes": "fresh"},
            {"name": "Garlic", "amount": "4 cloves", "notes": None},
        ],
        "instructions": [
            "Preheat oven to 425°F (220°C).",
            "Toss potatoes and green beans with 1 tbsp olive oil.",
            "Spread vegetables in a baking dish.",
            "Rub chicken with remaining oil, salt, pepper.",
            "Place chicken on top of vegetables.",
            "Add lemon slices, garlic, and herbs.",
            "Roast 40-45 minutes until chicken is cooked through.",
        ],
        "diet_tags": [DietTag.HIGH_PROTEIN, DietTag.GLUTEN_FREE, DietTag.DAIRY_FREE, DietTag.PALEO],
        "is_featured": False,
    },
    {
        "name": "Steak with Sweet Potato",
        "description": "Perfectly cooked sirloin steak with loaded sweet potato.",
        "meal_type": MealType.DINNER,
        "prep_time_minutes": 10,
        "cook_time_minutes": 30,
        "servings": 1,
        "calories": 520,
        "protein_g": 42,
        "carbs_g": 38,
        "fat_g": 22,
        "fiber_g": 6,
        "sugar_g": 8,
        "ingredients": [
            {"name": "Sirloin steak", "amount": "6 oz", "notes": None},
            {"name": "Sweet potato", "amount": "1 medium", "notes": None},
            {"name": "Butter", "amount": "1 tbsp", "notes": None},
            {"name": "Greek yogurt", "amount": "2 tbsp", "notes": None},
            {"name": "Chives", "amount": "1 tbsp", "notes": "chopped"},
            {"name": "Olive oil", "amount": "1 tsp", "notes": None},
        ],
        "instructions": [
            "Pierce sweet potato and microwave 5-7 minutes until tender.",
            "Season steak generously with salt and pepper.",
            "Heat cast iron skillet over high heat.",
            "Sear steak 3-4 minutes per side for medium-rare.",
            "Rest steak 5 minutes before slicing.",
            "Split sweet potato, add butter and yogurt.",
            "Serve steak alongside loaded sweet potato.",
        ],
        "diet_tags": [DietTag.HIGH_PROTEIN, DietTag.GLUTEN_FREE, DietTag.POST_WORKOUT],
        "is_featured": False,
    },
    {
        "name": "Shrimp Cauliflower Fried Rice",
        "description": "Low-carb twist on fried rice using cauliflower rice and plump shrimp.",
        "meal_type": MealType.DINNER,
        "prep_time_minutes": 15,
        "cook_time_minutes": 15,
        "servings": 2,
        "calories": 280,
        "protein_g": 28,
        "carbs_g": 14,
        "fat_g": 12,
        "fiber_g": 4,
        "sugar_g": 6,
        "ingredients": [
            {"name": "Large shrimp", "amount": "8 oz", "notes": "peeled"},
            {"name": "Cauliflower rice", "amount": "3 cups", "notes": "fresh or frozen"},
            {"name": "Eggs", "amount": "2", "notes": "beaten"},
            {"name": "Peas and carrots", "amount": "1/2 cup", "notes": "frozen"},
            {"name": "Green onions", "amount": "3", "notes": "sliced"},
            {"name": "Low sodium soy sauce", "amount": "2 tbsp", "notes": None},
            {"name": "Sesame oil", "amount": "1 tbsp", "notes": None},
            {"name": "Garlic", "amount": "2 cloves", "notes": "minced"},
        ],
        "instructions": [
            "Heat sesame oil in a large pan or wok.",
            "Cook shrimp until pink, 2-3 minutes. Set aside.",
            "Scramble eggs in pan, set aside.",
            "Add cauliflower rice, peas, carrots, and garlic.",
            "Cook 5-6 minutes until tender.",
            "Add soy sauce, shrimp, and eggs.",
            "Toss to combine, top with green onions.",
        ],
        "diet_tags": [DietTag.HIGH_PROTEIN, DietTag.LOW_CARB, DietTag.KETO, DietTag.DAIRY_FREE, DietTag.GLUTEN_FREE],
        "is_featured": True,
    },
    {
        "name": "Stuffed Bell Peppers",
        "description": "Colorful bell peppers stuffed with lean ground beef, rice, and cheese.",
        "meal_type": MealType.DINNER,
        "prep_time_minutes": 20,
        "cook_time_minutes": 40,
        "servings": 4,
        "calories": 350,
        "protein_g": 28,
        "carbs_g": 28,
        "fat_g": 14,
        "fiber_g": 4,
        "sugar_g": 8,
        "ingredients": [
            {"name": "Bell peppers", "amount": "4 large", "notes": "any color"},
            {"name": "Lean ground beef", "amount": "1 lb", "notes": "90% lean"},
            {"name": "Brown rice", "amount": "1 cup", "notes": "cooked"},
            {"name": "Diced tomatoes", "amount": "1 can", "notes": None},
            {"name": "Italian seasoning", "amount": "1 tsp", "notes": None},
            {"name": "Mozzarella cheese", "amount": "1 cup", "notes": "shredded"},
            {"name": "Onion", "amount": "1/2", "notes": "diced"},
            {"name": "Garlic", "amount": "2 cloves", "notes": "minced"},
        ],
        "instructions": [
            "Preheat oven to 375°F (190°C).",
            "Cut tops off peppers, remove seeds.",
            "Brown beef with onion and garlic, drain excess fat.",
            "Mix beef with rice, half the tomatoes, and seasoning.",
            "Stuff peppers with beef mixture.",
            "Place in baking dish, pour remaining tomatoes around.",
            "Cover with foil, bake 30 minutes.",
            "Uncover, top with cheese, bake 10 more minutes.",
        ],
        "diet_tags": [DietTag.HIGH_PROTEIN, DietTag.GLUTEN_FREE, DietTag.MEAL_PREP],
        "is_featured": False,
    },
    {
        "name": "Honey Garlic Chicken Thighs",
        "description": "Sweet and savory chicken thighs with a sticky honey garlic glaze.",
        "meal_type": MealType.DINNER,
        "prep_time_minutes": 10,
        "cook_time_minutes": 35,
        "servings": 2,
        "calories": 380,
        "protein_g": 32,
        "carbs_g": 24,
        "fat_g": 18,
        "fiber_g": 1,
        "sugar_g": 18,
        "ingredients": [
            {"name": "Chicken thighs", "amount": "4", "notes": "boneless"},
            {"name": "Honey", "amount": "3 tbsp", "notes": None},
            {"name": "Soy sauce", "amount": "3 tbsp", "notes": "low sodium"},
            {"name": "Garlic", "amount": "4 cloves", "notes": "minced"},
            {"name": "Rice vinegar", "amount": "1 tbsp", "notes": None},
            {"name": "Sesame seeds", "amount": "1 tsp", "notes": "for garnish"},
            {"name": "Green onions", "amount": "2", "notes": "sliced"},
        ],
        "instructions": [
            "Mix honey, soy sauce, garlic, and vinegar for sauce.",
            "Season chicken with salt and pepper.",
            "Sear chicken in a hot pan, 4-5 minutes per side.",
            "Pour sauce over chicken.",
            "Simmer 10-15 minutes until chicken is cooked and sauce thickens.",
            "Garnish with sesame seeds and green onions.",
            "Serve with rice and steamed vegetables.",
        ],
        "diet_tags": [DietTag.HIGH_PROTEIN, DietTag.DAIRY_FREE],
        "is_featured": False,
    },
    {
        "name": "Mediterranean Baked Cod",
        "description": "Flaky white fish baked with tomatoes, olives, and herbs. Heart-healthy and delicious.",
        "meal_type": MealType.DINNER,
        "prep_time_minutes": 15,
        "cook_time_minutes": 25,
        "servings": 2,
        "calories": 320,
        "protein_g": 36,
        "carbs_g": 12,
        "fat_g": 14,
        "fiber_g": 3,
        "sugar_g": 5,
        "ingredients": [
            {"name": "Cod fillets", "amount": "2 (6 oz each)", "notes": None},
            {"name": "Cherry tomatoes", "amount": "1 cup", "notes": "halved"},
            {"name": "Kalamata olives", "amount": "1/4 cup", "notes": "pitted"},
            {"name": "Capers", "amount": "2 tbsp", "notes": "drained"},
            {"name": "Olive oil", "amount": "2 tbsp", "notes": "extra virgin"},
            {"name": "Garlic", "amount": "3 cloves", "notes": "minced"},
            {"name": "Fresh basil", "amount": "1/4 cup", "notes": "chopped"},
            {"name": "Lemon juice", "amount": "2 tbsp", "notes": None},
        ],
        "instructions": [
            "Preheat oven to 400°F (200°C).",
            "Place cod fillets in a baking dish.",
            "Scatter tomatoes, olives, and capers around fish.",
            "Drizzle with olive oil and lemon juice.",
            "Sprinkle garlic over everything.",
            "Bake 20-25 minutes until fish flakes easily.",
            "Garnish with fresh basil and serve.",
        ],
        "diet_tags": [DietTag.HIGH_PROTEIN, DietTag.LOW_CARB, DietTag.MEDITERRANEAN, DietTag.GLUTEN_FREE, DietTag.DAIRY_FREE, DietTag.PALEO],
        "is_featured": False,
    },
    {
        "name": "Thai Basil Chicken",
        "description": "Aromatic stir-fry with ground chicken, Thai basil, and a savory-spicy sauce.",
        "meal_type": MealType.DINNER,
        "prep_time_minutes": 10,
        "cook_time_minutes": 15,
        "servings": 2,
        "calories": 380,
        "protein_g": 35,
        "carbs_g": 22,
        "fat_g": 16,
        "fiber_g": 2,
        "sugar_g": 8,
        "ingredients": [
            {"name": "Ground chicken", "amount": "1 lb", "notes": None},
            {"name": "Thai basil leaves", "amount": "1 cup", "notes": "packed"},
            {"name": "Garlic", "amount": "5 cloves", "notes": "minced"},
            {"name": "Thai chili", "amount": "2", "notes": "sliced, optional"},
            {"name": "Fish sauce", "amount": "2 tbsp", "notes": None},
            {"name": "Soy sauce", "amount": "1 tbsp", "notes": "low sodium"},
            {"name": "Brown sugar", "amount": "1 tbsp", "notes": None},
            {"name": "Vegetable oil", "amount": "2 tbsp", "notes": None},
            {"name": "Jasmine rice", "amount": "1 cup", "notes": "cooked, for serving"},
        ],
        "instructions": [
            "Heat oil in a wok or large pan over high heat.",
            "Add garlic and chilies, stir-fry 30 seconds.",
            "Add ground chicken, break up and cook until browned.",
            "Add fish sauce, soy sauce, and brown sugar.",
            "Stir-fry 2-3 minutes until sauce reduces slightly.",
            "Remove from heat and fold in Thai basil leaves.",
            "Serve immediately over jasmine rice.",
        ],
        "diet_tags": [DietTag.HIGH_PROTEIN, DietTag.DAIRY_FREE, DietTag.QUICK],
        "is_featured": False,
    },
    {
        "name": "Black Bean Veggie Tacos",
        "description": "Flavorful plant-based tacos with seasoned black beans and fresh toppings.",
        "meal_type": MealType.DINNER,
        "prep_time_minutes": 15,
        "cook_time_minutes": 10,
        "servings": 2,
        "calories": 420,
        "protein_g": 16,
        "carbs_g": 58,
        "fat_g": 14,
        "fiber_g": 14,
        "sugar_g": 6,
        "ingredients": [
            {"name": "Black beans", "amount": "1 can (15 oz)", "notes": "drained and rinsed"},
            {"name": "Corn tortillas", "amount": "6 small", "notes": None},
            {"name": "Avocado", "amount": "1", "notes": "sliced"},
            {"name": "Red cabbage", "amount": "1 cup", "notes": "shredded"},
            {"name": "Lime", "amount": "1", "notes": "cut into wedges"},
            {"name": "Cilantro", "amount": "1/4 cup", "notes": "chopped"},
            {"name": "Cumin", "amount": "1 tsp", "notes": None},
            {"name": "Chili powder", "amount": "1 tsp", "notes": None},
            {"name": "Salsa verde", "amount": "1/4 cup", "notes": None},
        ],
        "instructions": [
            "Heat black beans with cumin and chili powder in a pan.",
            "Mash slightly with a fork for texture.",
            "Warm tortillas in a dry pan or microwave.",
            "Divide beans among tortillas.",
            "Top with cabbage, avocado, and cilantro.",
            "Drizzle with salsa verde.",
            "Serve with lime wedges.",
        ],
        "diet_tags": [DietTag.VEGAN, DietTag.VEGETARIAN, DietTag.HIGH_PROTEIN, DietTag.GLUTEN_FREE, DietTag.DAIRY_FREE, DietTag.QUICK],
        "is_featured": False,
    },

    # ============ SNACKS (12 recipes) ============
    {
        "name": "Protein Energy Balls",
        "description": "No-bake energy balls packed with oats, protein, and peanut butter.",
        "meal_type": MealType.SNACK,
        "prep_time_minutes": 15,
        "cook_time_minutes": 0,
        "servings": 12,
        "calories": 120,
        "protein_g": 6,
        "carbs_g": 14,
        "fat_g": 5,
        "fiber_g": 2,
        "sugar_g": 6,
        "ingredients": [
            {"name": "Rolled oats", "amount": "1 cup", "notes": None},
            {"name": "Protein powder", "amount": "1/2 cup", "notes": "vanilla"},
            {"name": "Peanut butter", "amount": "1/2 cup", "notes": None},
            {"name": "Honey", "amount": "1/4 cup", "notes": None},
            {"name": "Mini chocolate chips", "amount": "2 tbsp", "notes": None},
            {"name": "Chia seeds", "amount": "1 tbsp", "notes": None},
        ],
        "instructions": [
            "Mix all ingredients in a large bowl.",
            "Refrigerate 15 minutes until firm enough to roll.",
            "Roll into 12 balls (about 1 inch each).",
            "Store in fridge for up to 1 week.",
        ],
        "diet_tags": [DietTag.HIGH_PROTEIN, DietTag.VEGETARIAN, DietTag.MEAL_PREP, DietTag.POST_WORKOUT],
        "is_featured": True,
    },
    {
        "name": "Cucumber Hummus Bites",
        "description": "Fresh cucumber slices topped with hummus and everything bagel seasoning.",
        "meal_type": MealType.SNACK,
        "prep_time_minutes": 5,
        "cook_time_minutes": 0,
        "servings": 1,
        "calories": 120,
        "protein_g": 5,
        "carbs_g": 12,
        "fat_g": 6,
        "fiber_g": 3,
        "sugar_g": 3,
        "ingredients": [
            {"name": "Cucumber", "amount": "1 medium", "notes": "sliced thick"},
            {"name": "Hummus", "amount": "3 tbsp", "notes": None},
            {"name": "Everything bagel seasoning", "amount": "1 tsp", "notes": None},
            {"name": "Cherry tomatoes", "amount": "3", "notes": "halved"},
        ],
        "instructions": [
            "Slice cucumber into 1/2 inch thick rounds.",
            "Top each slice with a dollop of hummus.",
            "Add a tomato half on top.",
            "Sprinkle with everything bagel seasoning.",
        ],
        "diet_tags": [DietTag.VEGAN, DietTag.VEGETARIAN, DietTag.LOW_CARB, DietTag.QUICK, DietTag.GLUTEN_FREE],
        "is_featured": False,
    },
    {
        "name": "Apple Almond Butter Slices",
        "description": "Crisp apple slices with almond butter and a sprinkle of cinnamon.",
        "meal_type": MealType.SNACK,
        "prep_time_minutes": 3,
        "cook_time_minutes": 0,
        "servings": 1,
        "calories": 200,
        "protein_g": 5,
        "carbs_g": 26,
        "fat_g": 10,
        "fiber_g": 5,
        "sugar_g": 18,
        "ingredients": [
            {"name": "Apple", "amount": "1 medium", "notes": "any variety"},
            {"name": "Almond butter", "amount": "2 tbsp", "notes": None},
            {"name": "Cinnamon", "amount": "1/4 tsp", "notes": None},
            {"name": "Hemp hearts", "amount": "1 tsp", "notes": "optional"},
        ],
        "instructions": [
            "Core and slice apple into wedges.",
            "Spread almond butter on each slice.",
            "Sprinkle with cinnamon and hemp hearts.",
            "Serve immediately.",
        ],
        "diet_tags": [DietTag.VEGAN, DietTag.VEGETARIAN, DietTag.QUICK, DietTag.GLUTEN_FREE, DietTag.PALEO],
        "is_featured": False,
    },
    {
        "name": "Greek Yogurt Parfait",
        "description": "Layered Greek yogurt with granola and fresh berries. Perfect afternoon pick-me-up.",
        "meal_type": MealType.SNACK,
        "prep_time_minutes": 5,
        "cook_time_minutes": 0,
        "servings": 1,
        "calories": 220,
        "protein_g": 18,
        "carbs_g": 28,
        "fat_g": 4,
        "fiber_g": 3,
        "sugar_g": 16,
        "ingredients": [
            {"name": "Greek yogurt (0% fat)", "amount": "3/4 cup", "notes": "plain"},
            {"name": "Granola", "amount": "2 tbsp", "notes": "low sugar"},
            {"name": "Strawberries", "amount": "1/4 cup", "notes": "sliced"},
            {"name": "Blueberries", "amount": "2 tbsp", "notes": None},
            {"name": "Honey", "amount": "1 tsp", "notes": "optional"},
        ],
        "instructions": [
            "Layer half the yogurt in a glass or jar.",
            "Add half the berries and granola.",
            "Repeat layers with remaining ingredients.",
            "Drizzle with honey if desired.",
            "Serve immediately or refrigerate up to 4 hours.",
        ],
        "diet_tags": [DietTag.HIGH_PROTEIN, DietTag.VEGETARIAN, DietTag.QUICK],
        "is_featured": False,
    },
    {
        "name": "Edamame with Sea Salt",
        "description": "Steamed edamame pods with a sprinkle of sea salt. Simple, satisfying protein boost.",
        "meal_type": MealType.SNACK,
        "prep_time_minutes": 2,
        "cook_time_minutes": 5,
        "servings": 1,
        "calories": 120,
        "protein_g": 11,
        "carbs_g": 9,
        "fat_g": 5,
        "fiber_g": 4,
        "sugar_g": 2,
        "ingredients": [
            {"name": "Frozen edamame in pods", "amount": "1 cup", "notes": None},
            {"name": "Sea salt", "amount": "1/4 tsp", "notes": "flaky"},
            {"name": "Lemon zest", "amount": "1/4 tsp", "notes": "optional"},
        ],
        "instructions": [
            "Steam or microwave edamame until heated through, about 5 minutes.",
            "Drain any excess water.",
            "Toss with sea salt and optional lemon zest.",
            "Serve warm in a bowl.",
            "Squeeze pods to eat the beans inside.",
        ],
        "diet_tags": [DietTag.VEGAN, DietTag.VEGETARIAN, DietTag.HIGH_PROTEIN, DietTag.QUICK, DietTag.GLUTEN_FREE],
        "is_featured": False,
    },
    {
        "name": "Cottage Cheese & Berries",
        "description": "Creamy cottage cheese topped with mixed berries and a drizzle of honey.",
        "meal_type": MealType.SNACK,
        "prep_time_minutes": 3,
        "cook_time_minutes": 0,
        "servings": 1,
        "calories": 180,
        "protein_g": 20,
        "carbs_g": 18,
        "fat_g": 3,
        "fiber_g": 2,
        "sugar_g": 14,
        "ingredients": [
            {"name": "Cottage cheese (2%)", "amount": "3/4 cup", "notes": None},
            {"name": "Mixed berries", "amount": "1/2 cup", "notes": "fresh or thawed"},
            {"name": "Honey", "amount": "1 tsp", "notes": None},
            {"name": "Mint leaves", "amount": "2-3", "notes": "optional garnish"},
        ],
        "instructions": [
            "Add cottage cheese to a bowl.",
            "Top with mixed berries.",
            "Drizzle with honey.",
            "Garnish with mint leaves if desired.",
        ],
        "diet_tags": [DietTag.HIGH_PROTEIN, DietTag.VEGETARIAN, DietTag.QUICK, DietTag.GLUTEN_FREE, DietTag.LOW_CARB],
        "is_featured": False,
    },
    {
        "name": "Turkey & Cheese Roll-Ups",
        "description": "Lean turkey slices wrapped around cheese sticks. Zero-carb protein snack.",
        "meal_type": MealType.SNACK,
        "prep_time_minutes": 3,
        "cook_time_minutes": 0,
        "servings": 1,
        "calories": 150,
        "protein_g": 18,
        "carbs_g": 2,
        "fat_g": 8,
        "fiber_g": 0,
        "sugar_g": 1,
        "ingredients": [
            {"name": "Turkey breast slices", "amount": "3 oz", "notes": "low sodium"},
            {"name": "String cheese", "amount": "1 stick", "notes": "part-skim mozzarella"},
            {"name": "Mustard", "amount": "1 tsp", "notes": "optional"},
        ],
        "instructions": [
            "Lay turkey slices flat.",
            "Spread thin layer of mustard if using.",
            "Place cheese stick at one end.",
            "Roll turkey tightly around cheese.",
            "Cut in half for easier eating.",
        ],
        "diet_tags": [DietTag.HIGH_PROTEIN, DietTag.LOW_CARB, DietTag.KETO, DietTag.QUICK, DietTag.GLUTEN_FREE],
        "is_featured": False,
    },
    {
        "name": "Hard Boiled Eggs with Everything",
        "description": "Perfectly cooked hard boiled eggs with everything bagel seasoning.",
        "meal_type": MealType.SNACK,
        "prep_time_minutes": 2,
        "cook_time_minutes": 12,
        "servings": 1,
        "calories": 160,
        "protein_g": 14,
        "carbs_g": 1,
        "fat_g": 11,
        "fiber_g": 0,
        "sugar_g": 1,
        "ingredients": [
            {"name": "Eggs", "amount": "2 large", "notes": None},
            {"name": "Everything bagel seasoning", "amount": "1 tsp", "notes": None},
            {"name": "Hot sauce", "amount": "to taste", "notes": "optional"},
        ],
        "instructions": [
            "Place eggs in a pot, cover with cold water.",
            "Bring to a boil, then cover and remove from heat.",
            "Let sit 10-12 minutes for hard boiled.",
            "Transfer to ice bath to cool.",
            "Peel, slice in half, and sprinkle with seasoning.",
            "Add hot sauce if desired.",
        ],
        "diet_tags": [DietTag.HIGH_PROTEIN, DietTag.LOW_CARB, DietTag.KETO, DietTag.GLUTEN_FREE, DietTag.PALEO, DietTag.DAIRY_FREE, DietTag.MEAL_PREP],
        "is_featured": True,
    },
    {
        "name": "Crispy Roasted Chickpeas",
        "description": "Crunchy spiced chickpeas roasted until golden. Satisfying savory snack.",
        "meal_type": MealType.SNACK,
        "prep_time_minutes": 5,
        "cook_time_minutes": 35,
        "servings": 4,
        "calories": 140,
        "protein_g": 6,
        "carbs_g": 20,
        "fat_g": 4,
        "fiber_g": 5,
        "sugar_g": 4,
        "ingredients": [
            {"name": "Chickpeas", "amount": "1 can (15 oz)", "notes": "drained and dried"},
            {"name": "Olive oil", "amount": "1 tbsp", "notes": None},
            {"name": "Smoked paprika", "amount": "1 tsp", "notes": None},
            {"name": "Garlic powder", "amount": "1/2 tsp", "notes": None},
            {"name": "Salt", "amount": "1/2 tsp", "notes": None},
            {"name": "Cayenne pepper", "amount": "1/4 tsp", "notes": "optional"},
        ],
        "instructions": [
            "Preheat oven to 400°F (200°C).",
            "Pat chickpeas very dry with paper towels.",
            "Toss with olive oil and spices.",
            "Spread on a baking sheet in single layer.",
            "Roast 30-35 minutes, shaking pan halfway.",
            "Let cool completely for maximum crispiness.",
            "Store in airtight container up to 5 days.",
        ],
        "diet_tags": [DietTag.VEGAN, DietTag.VEGETARIAN, DietTag.HIGH_PROTEIN, DietTag.GLUTEN_FREE, DietTag.DAIRY_FREE, DietTag.MEAL_PREP],
        "is_featured": False,
    },
    {
        "name": "Chocolate Chia Pudding",
        "description": "Creamy chocolate pudding made with chia seeds. Prep ahead for a healthy treat.",
        "meal_type": MealType.SNACK,
        "prep_time_minutes": 5,
        "cook_time_minutes": 0,
        "servings": 2,
        "calories": 180,
        "protein_g": 8,
        "carbs_g": 22,
        "fat_g": 8,
        "fiber_g": 10,
        "sugar_g": 8,
        "ingredients": [
            {"name": "Chia seeds", "amount": "1/4 cup", "notes": None},
            {"name": "Almond milk", "amount": "1 cup", "notes": "unsweetened"},
            {"name": "Cocoa powder", "amount": "2 tbsp", "notes": "unsweetened"},
            {"name": "Maple syrup", "amount": "1 tbsp", "notes": None},
            {"name": "Vanilla extract", "amount": "1/2 tsp", "notes": None},
            {"name": "Raspberries", "amount": "1/4 cup", "notes": "for topping"},
        ],
        "instructions": [
            "Whisk together almond milk, cocoa powder, maple syrup, and vanilla.",
            "Stir in chia seeds thoroughly.",
            "Refrigerate at least 4 hours or overnight.",
            "Stir well before serving.",
            "Top with fresh raspberries.",
        ],
        "diet_tags": [DietTag.VEGAN, DietTag.VEGETARIAN, DietTag.GLUTEN_FREE, DietTag.DAIRY_FREE, DietTag.MEAL_PREP],
        "is_featured": False,
    },
    {
        "name": "Celery with Peanut Butter & Raisins",
        "description": "Classic 'ants on a log' snack. Crunchy, creamy, and naturally sweet.",
        "meal_type": MealType.SNACK,
        "prep_time_minutes": 5,
        "cook_time_minutes": 0,
        "servings": 1,
        "calories": 210,
        "protein_g": 7,
        "carbs_g": 20,
        "fat_g": 13,
        "fiber_g": 3,
        "sugar_g": 14,
        "ingredients": [
            {"name": "Celery stalks", "amount": "3 large", "notes": "washed"},
            {"name": "Peanut butter", "amount": "2 tbsp", "notes": "natural"},
            {"name": "Raisins", "amount": "1 tbsp", "notes": None},
        ],
        "instructions": [
            "Cut celery stalks into 4-inch pieces.",
            "Fill the groove with peanut butter.",
            "Press raisins into the peanut butter.",
            "Serve immediately or chill until ready.",
        ],
        "diet_tags": [DietTag.VEGAN, DietTag.VEGETARIAN, DietTag.QUICK, DietTag.GLUTEN_FREE, DietTag.DAIRY_FREE],
        "is_featured": False,
    },
    {
        "name": "Caprese Skewers",
        "description": "Cherry tomatoes, fresh mozzarella, and basil on toothpicks with balsamic drizzle.",
        "meal_type": MealType.SNACK,
        "prep_time_minutes": 10,
        "cook_time_minutes": 0,
        "servings": 2,
        "calories": 140,
        "protein_g": 8,
        "carbs_g": 6,
        "fat_g": 10,
        "fiber_g": 1,
        "sugar_g": 4,
        "ingredients": [
            {"name": "Cherry tomatoes", "amount": "8", "notes": None},
            {"name": "Fresh mozzarella balls", "amount": "8 small", "notes": "ciliegine"},
            {"name": "Fresh basil leaves", "amount": "8", "notes": None},
            {"name": "Balsamic glaze", "amount": "1 tbsp", "notes": None},
            {"name": "Olive oil", "amount": "1 tsp", "notes": "extra virgin"},
            {"name": "Salt and pepper", "amount": "to taste", "notes": None},
        ],
        "instructions": [
            "Thread a tomato, basil leaf, and mozzarella ball on each toothpick.",
            "Arrange on a serving plate.",
            "Drizzle with olive oil and balsamic glaze.",
            "Season with salt and pepper.",
            "Serve immediately.",
        ],
        "diet_tags": [DietTag.VEGETARIAN, DietTag.LOW_CARB, DietTag.KETO, DietTag.QUICK, DietTag.GLUTEN_FREE, DietTag.MEDITERRANEAN],
        "is_featured": True,
    },
]


async def seed_recipes():
    """Seed recipes into the database."""
    engine = create_async_engine(DATABASE_URL)
    async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

    async with async_session() as session:
        # Check if recipes already exist
        result = await session.execute(select(RecipeORM).limit(1))
        if result.scalar_one_or_none():
            print("Recipes already seeded. Skipping.")
            return

        now = datetime.now(UTC)
        for recipe_data in RECIPES:
            recipe = RecipeORM(
                id=str(uuid.uuid4()),
                name=recipe_data["name"],
                description=recipe_data["description"],
                meal_type=recipe_data["meal_type"],
                prep_time_minutes=recipe_data["prep_time_minutes"],
                cook_time_minutes=recipe_data["cook_time_minutes"],
                servings=recipe_data["servings"],
                calories=recipe_data["calories"],
                protein_g=recipe_data["protein_g"],
                carbs_g=recipe_data["carbs_g"],
                fat_g=recipe_data["fat_g"],
                fiber_g=recipe_data.get("fiber_g"),
                sugar_g=recipe_data.get("sugar_g"),
                ingredients=recipe_data["ingredients"],
                instructions=recipe_data["instructions"],
                diet_tags=[tag.value for tag in recipe_data["diet_tags"]],
                is_featured=recipe_data.get("is_featured", False),
                times_saved=0,
                total_rating=0.0,
                rating_count=0,
                created_at=now,
                updated_at=now,
            )
            session.add(recipe)

        await session.commit()
        print(f"Successfully seeded {len(RECIPES)} recipes!")


if __name__ == "__main__":
    asyncio.run(seed_recipes())
